version: '3.9'

services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=moradaDb
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123
    ports:
      - '5432:5432'

  api:
    build:
      context: .
      dockerfile: dockerfile
    image: micaelortega/morada-app-api
    depends_on:
      - db
    volumes:
      - .:/app
      - ${pwd}/node_modules
    ports:
      - '3000:3000'
